# Generated by Django 4.1.5 on 2023-01-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('common_name', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=125, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('continent', models.CharField(blank=True, max_length=30, null=True)),
                ('country_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('season', models.JSONField(blank=True, null=True)),
                ('standing', models.JSONField(blank=True, null=True)),
                ('matches', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clubs',
                'managed': False,
            },
        ),
    ]
