"""Added CFC DB - Club - addMethod

Revision ID: 4964be79683d
Revises: 5bb16aa6a908
Create Date: 2022-11-02 16:07:47.793331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4964be79683d'
down_revision = '5bb16aa6a908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
