"""Added CFC DB - Club

Revision ID: 5bb16aa6a908
Revises: a4ec26fe5498
Create Date: 2022-11-02 00:05:33.142732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb16aa6a908'
down_revision = 'a4ec26fe5498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=5), nullable=True),
    sa.Column('continent', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clubs')
    # ### end Alembic commands ###
