"""Added primary fields - fixed standings

Revision ID: 699130536e40
Revises: de065e234f75
Create Date: 2023-01-04 12:07:54.628771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699130536e40'
down_revision = 'de065e234f75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
