"""added fields

Revision ID: ae396b076779
Revises: 
Create Date: 2023-01-10 16:04:19.002726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae396b076779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('short_code', sa.String(length=5), nullable=True),
    sa.Column('common_name', sa.String(length=30), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('country_name', sa.String(length=125), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('continent', sa.String(length=30), nullable=True),
    sa.Column('country_flag', sa.String(length=255), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.JSON(), nullable=True),
    sa.Column('standing', sa.JSON(), nullable=True),
    sa.Column('matches', sa.JSON(), nullable=True),
    sa.Column('biography', sa.String(length=65651), nullable=True),
    sa.Column('trophies', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clubs')
    # ### end Alembic commands ###
