"""Added CFC DB - Club - addMethod - added fix columns

Revision ID: c24691a10669
Revises: c8a8f5af7ca1
Create Date: 2022-11-02 19:37:20.642103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24691a10669'
down_revision = 'c8a8f5af7ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clubs', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('Clubs', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('Clubs', sa.Column('common_name', sa.String(length=30), nullable=True))
    op.add_column('Clubs', sa.Column('logo', sa.String(length=255), nullable=True))
    op.add_column('Clubs', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('Clubs', sa.Column('country_name', sa.String(length=125), nullable=True))
    op.add_column('Clubs', sa.Column('country_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clubs', 'country_code')
    op.drop_column('Clubs', 'country_name')
    op.drop_column('Clubs', 'country_id')
    op.drop_column('Clubs', 'logo')
    op.drop_column('Clubs', 'common_name')
    op.drop_column('Clubs', 'name')
    op.drop_column('Clubs', 'team_id')
    # ### end Alembic commands ###
