"""Added CFC DB - Club - addMethod - test

Revision ID: c8a8f5af7ca1
Revises: 4964be79683d
Create Date: 2022-11-02 19:33:20.249405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a8f5af7ca1'
down_revision = '4964be79683d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
