import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";

export default function Home() {
  const [clubs, setClubs] = useState([]);
  const [club, setClub] = useState("");
  function GetClubs_ByAPI() {
    fetch("http://127.0.0.1:8000/api-data/clubs/")
      .then((res) => res.json())
      .then((result) => {
        setClubs(result);
        console.log(result);
      });
  }

  useEffect(() => {
    GetClubs_ByAPI();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar clubs={clubs} setClub={setClub} />
        {club}
      </main>
    </>
  );
}
