state = [
	"Padding List",
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "St. Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Bismarck",
    "Columbus",
    "Oklahoma City",
    "Salem",
    "Harrisburg",
    "Providence",
    "Columbia",
    "Pierre",
    "Nashville",
    "Austin",
    "Salt Lake City",
    "Montpelier",
    "Richmond",
    "Olympia",
    "Charleston",
    "Madison",
    "Cheyenne",
]

QUIZ = [
    ["Alabama", [state[1], state[29], state[6], state[43]]],
    ["Alaska", [state[2], state[31], state[23], state[27]]],
    ["Arizona", [state[3], state[24], state[23], state[15]]],
    ["Arkansas", [state[4], state[20], state[13], state[45]]],
    ["California", [state[5], state[14], state[4], state[37]]],
    ["Colorado", [state[6], state[14], state[4], state[37]]],
    ["Connecticut", [state[7], state[42], state[48], state[20]]],
    ["Delaware", [state[8], state[39], state[34], state[4]]],
    ["Florida", [state[9], state[4], state[23], state[35]]],
    ["Georgia", [state[10], state[39], state[21], state[26]]],
    ["Hawaii", [state[11], state[15], state[1], state[35]]],
    ["Idaho", [state[12], state[50], state[42], state[34]]],
    ["Illinois", [state[13], state[9], state[10], state[44]]],
    ["Indiana", [state[14], state[44], state[9], state[6]]],
    ["Iowa", [state[15], state[42], state[38], state[33]]],
    ["Kansas", [state[16], state[24], state[11], state[32]]],
    ["Kentucky", [state[17], state[38], state[9], state[30]]],
    ["Louisiana", [state[18], state[10], state[26], state[37]]],
    ["Maine", [state[19], state[46], state[31], state[42]]],
    ["Maryland", [state[20], state[47], state[32], state[17]]],
    ["Massachusetts", [state[21], state[35], state[47], state[34]]],
    ["Michigan", [state[22], state[3], state[44], state[2]]],
    ["Minnesota", [state[23], state[44], state[32], state[35]]],
    ["Mississippi", [state[24], state[47], state[34], state[50]]],
    ["Missouri", [state[25], state[32], state[44], state[17]]],
    ["Montana", [state[26], state[6], state[12], state[14]]],
    ["Nebraska", [state[27], state[15], state[42], state[40]]],
    ["Nevada", [state[28], state[45], state[41], state[3]]],
    ["New Hampshire", [state[29], state[12], state[11], state[43]]],
    ["New Jersey", [state[30], state[8], state[37], state[19]]],
    ["New Mexico", [state[31], state[50], state[39], state[13]]],
    ["New York", [state[32], state[37], state[2], state[15]]],
    ["North Carolina", [state[33], state[6], state[49], state[23]]],
    ["North Dakota", [state[34], state[21], state[13], state[29]]],
    ["Ohio", [state[35], state[36], state[47], state[31]]],
    ["Oklahoma", [state[36], state[2], state[44], state[47]]],
    ["Oregon", [state[37], state[26], state[27], state[34]]],
    ["Pennsylvania", [state[38], state[35], state[33], state[36]]],
    ["Rhode Island", [state[39], state[46], state[11], state[3]]],
    ["South Carolina", [state[40], state[31], state[49], state[8]]],
    ["South Dakota", [state[41], state[50], state[19], state[6]]],
    ["Tennessee", [state[42], state[40], state[29], state[15]]],
    ["Texas", [state[43], state[15], state[24], state[4]]],
    ["Utah", [state[44], state[37], state[15], state[46]]],
    ["Vermont", [state[45], state[42], state[17], state[40]]],
    ["Virginia", [state[46], state[49], state[19], state[33]]],
    ["Washington", [state[47], state[17], state[3], state[40]]],
    ["West Virginia", [state[48], state[44], state[14], state[5]]],
    ["Wisconsin", [state[49], state[48], state[5], state[37]]],
    ["Wyoming", [state[50], state[41], state[7], state[14]]],
]

LEVELS = {"1": [1, 10], "2": [11, 100], "3": [101, 1000]}

OPERATORS = ["+", "-", "*", "/"]

CATEGORIES = [
    "Category 1: Technology, Science, Geography, History, Modern Literature",
    "Category 2: Comics, Movies & TV, Music, Fashion, Design",
    "Category 3: Cars, Sports, Games, Food & Drinks, Human Health",
    "Category 4: People, Celebrities, Performing Arts, Politics, Law",
    "Category 5: Riddles, Holidays, Religion, Mythology, Animals",
]


TRIVIA = {
    "Category 1": [
        ["What year was the very first model of the iPhone released?", "2007"],
        ["What’s the shortcut for the “copy” function on most computers?", "ctrl c"],
        ["What is often seen as the smallest unit of memory?", "kilobyte"],
        ["Is Java a type of Operating System?", "No"],
        ["Who is often called the father of the computer?", "Charles Babbage"],
        ["What does “HTTP” stand for?", "HyperText Transfer Protocol"],
        [
            "What is the name of the man who launched eBay back in 1995?",
            "Pierre Omidyar",
        ],
        ["Which email service is owned by Microsoft?", "Hotmail"],
        [
            "Google Chrome, Safari, Firefox, and Explorer are different types of what?",
            "Web browsers",
        ],
        ["What was Twitter’s original name?", "twttr"],
        ["Who discovered penicillin?", "Alexander Fleming"],
        ["Who was the first woman to win a Nobel Prize (in 1903)?", "Marie Curie"],
        ["What part of the atom has no electric charge?", "Neutron"],
        ["What is the symbol for potassium?", "K"],
        ["What is meteorology the study of?", "The weather"],
        ["Which planet is the hottest in the solar system?", "Venus"],
        ["Which natural disaster is measured with a Richter scale?", "Earthquakes"],
        ["What animals are pearls found in?", "Oysters"],
        ["Which planet has the most gravity?", "Jupiter"],
        ["How many molecules of oxygen does ozone have?", "Three"],
        [
            "What is the name of the thin and long country that spans more than half of the western coast of South America?",
            "Chile",
        ],
        ["Which American state is the largest (by area)?", "Alaska"],
        [
            "Which two countries share the longest international border?",
            "Canada and the USA",
        ],
        ["What is the smallest country in the world?", "Vatican City"],
        ["Which continent is the largest?", "Asia"],
        ["Which of the Seven Wonders is located in Egypt?", "The Pyramids of Giza"],
        ["What is the capital of New Zealand?", "Wellington"],
        [
            "Which desert is the largest in the world, excluding Antarctica?",
            "The Sahara Desert",
        ],
        ["What is the name of the world’s longest river?", "The Nile"],
        ["Which city in India would you find the Taj Mahal in?", "Agra"],
        ["By what name were the Egyptian kings/rulers known?", "Pharaohs"],
        ["How many Pyramids of Giza were made?", "Three"],
        ["Who which queen was Julius Caesar involved with?", "Cleopatra"],
        ["Where did the Franks settle after defeating the Romans?", "Gaul"],
        ["How long did the Middle Ages last?", "About 1000 years"],
        ["Which religion dominated the Middle Ages?", "Catholicism"],
        ["In which year World War I begin?", "1914"],
        ["In which country Adolph Hitler was born?", "Austria"],
        ["John F. Kennedy was assassinated in which city?", "Dallas"],
        [
            "On Sunday 18th June 1815, which famous battle took place?",
            "The Battle of Waterloo",
        ],
        [
            "What author became famous for his six-volume biography of Lincoln?",
            "Carl Sandburg",
        ],
        [
            "Who wrote “Old Man and The Sea” and is considered one of the greatest writers of the 20thcentury?",
            "Ernest Hemingway",
        ],
        [
            "What Danish author is considered by many to be the most prolific fairy tale writer?",
            "Hans Christian Andersen",
        ],
        ["Who is the writer of “Merchant of Venice”?", "William Shakespeare"],
        [
            "“Adventure of Sherlock Holmes” was written by which writer?",
            "Arthur Conan Doyle",
        ],
        [
            "What is the name of the fourth book in the Harry Potter series?",
            "Harry Potter and the Goblet of Fire",
        ],
        ["The Hunger Games series was written by which author?", "Suzanne Collins"],
        ["Which country is Aesop’s Fables believed to originate in?", "Greece"],
        [
            "In Herman Melville’s novel “Moby Dick,” who was the loyal, reasonable first mate?",
            "Starbuck",
        ],
        ["The book “Da Vinci Code,” was written by whom?", "Dan Brown"],
    ],
    "Category 2": [
        ["What is Hawkeye’s real name?", "Clint Barton"],
        ["Which Avenger is the only one who could calm the Hulk down?", "Black Widow"],
        [
            "Night Crawler, member of the X-Men, has what kind of powers?",
            "Can teleport",
        ],
        ["Which infinity stone was located on Vormir?", "Soul Stone"],
        ["Which original Avenger was not in the first few movies?", "The Wasp"],
        ["What was Superman’s birth name?", "Kal-El"],
        ["What is the name of Batman’s butler?", "Alfred"],
        ["Aquaman is from which city under the sea?", "Atlantis"],
        ["Who is Green Lantern’s nemesis?", "Sinestro"],
        ["What does DC stand for?", "Detective Comics"],
        [
            "What is the name of the song that Queen Elsa sings as she builds her ice castle in the movie Frozen?",
            "Let It Go",
        ],
        ["How many films did Sean Connery play James Bond in?", "Seven"],
        [
            "Which Indiana Jones movie was released back in 1984?",
            "Indiana Jones and the Temple of Doom",
        ],
        ["How many Lord of the Rings films are there?", "Three"],
        [
            "What was the name of the actor who played Jack Dawson in Titanic?",
            "Leonardo DiCaprio",
        ],
        [
            "Which popular TV show featured house Targaryen and Stark?",
            "Game of Thrones",
        ],
        ["What was the name of the family who starred in 7th Heaven?", "The Camdens"],
        [
            "Which cartoon character lives in a pineapple under the sea?",
            "Spongebob Squarepants",
        ],
        ["In what year was the first episode of South Park aired?", "1997"],
        [
            "What was the name of the group Justin Timberlake used to be part of?",
            "N’ SYNC",
        ],
        ["What was the name of the rock band formed by Jimmy Page?", "Led Zeppelin"],
        ["Which country did AC/DC originate in?", "Australia"],
        ["What genre of music did Taylor Swift start in?", "Country"],
        [
            "Who was the lead singer of the iconic ‘80s band, Culture Club?",
            "Boy George",
        ],
        ["Which name is rapper Sean Combs better known by?", "P. Diddy"],
        ["Which musical legend is Jay-Z married to?", "Beyonce"],
        ["How many Grammys does John Legend have?", "Ten"],
        ["Which British girl group had a member by the name of Mel B?", "Spice Girls"],
        [
            "Which song by Luis Fonsi and Daddy Yankee has the most views (of all time) on YouTube?",
            "Despacito",
        ],
        ["What is the tallest building in the world?", "Burj Khalifa"],
        ["When did construction on the Empire State building started?"],
        "1929",
        ["Who designed the Sydney Opera House?", "Jorn Utzon"],
        ["Between 1933 to 1947, the Hoover Dam was called what?", "Boulder Dam"],
        ["Where can you find the Petronas Towers?", "Kuala Lumpur"],
        ["Who invented the bidet?", "Christophe Des Rosiers"],
        ["What is the smallest size bed available in the United States?", "Twin"],
        ["Stripes, chevron, floral, and plaid are examples of what?", "Patterns"],
        ["What design style uses lots of sea/ocean themed items?", "Nautical"],
        ["What’s another name for a footrest?", "Ottoman"],
        [
            "Who is seen as the most famous female American fashion icon of the 1960’s?",
            "Jacqueline Kennedy",
        ],
        [
            "The American designer born in 1939 as Ralph Lifshitz is better known as what?",
            "Ralph Lauren",
        ],
        ["According to the commercial, “what is the fabric of our lives”?", "Cotton"],
        ["Who invented the LBD (little black dress)?", "Coco Chanel"],
        [
            "Parkers, trenches, bombers and peas are types of what winter outerwear?",
            "Coats",
        ],
        ["What fashion fad did the 1983 film “Flashdance” make popular?", "Legwarmers"],
        ["The fashion designer, Gianni Versace, came from which country?", "Italy"],
        ["When was the company Nike founded?", "1971"],
        ["What animal is on Levi’s logo?", "Horse"],
        [
            "Which fashion brand made the “Genius Jeans” that became part of the Guinness World Records?",
            "Gucci",
        ],
    ],
    "Category 3": [
        ["Who is often credited with creating the world’s first car?", "Karl Benz"],
        ["Which animal can be seen on the Porsche logo?", "Horse"],
        [
            "Which companies are part of the Big Three?",
            "General Motors, Fiat Chrysler Automobiles, and Ford Motor Company",
        ],
        [
            "Which company owns Bugatti, Lamborghini. Audi, Porsche, and Ducati?",
            "Volkswagen",
        ],
        ["Which auto brand was the first to offer seat belts?", "Nash Motors"],
        ["What does BMW stand for (in English)?", "Bavarian Motor Works"],
        ["What or who is the Ford Mustang named after?", "A fighter plane from WWII"],
        [
            "How many parts (screws and bolts included) does the average car have?",
            "30000",
        ],
        ["Which car is often called the first muscle car?", "The Pontiac GTO"],
        ["In what year was the Corvette introduced?", "1953"],
        [
            "How many soccer players should each team have on the field at the start of each match?",
            "11",
        ],
        [
            "When Michael Jordan played for the Chicago Bulls, how many NBA Championships did he win?",
            "Six",
        ],
        ["Which Williams sister has won more Grand Slam titles?", "Serena"],
        ["What country won the very first FIFA World Cup in 1930?", "Uruguay"],
        ["In what year was the first-ever Wimbledon Championship held?", "1877"],
        [
            "Which racer holds the record for the most Grand Prix wins?",
            "Michael Schumacher",
        ],
        [
            "Which Jamaican runner is an 11-time world champion and holds the record in the 100 and 200-meter race?",
            "Usain Bolt",
        ],
        [
            "Which boxer was known as “The Greatest” and “The People’s Champion”?",
            "Muhammad Ali",
        ],
        ["What sport was Jesse Owens involved in?", "Track and field"],
        [
            "Which hockey team did Wayne Gretzky play for in the ‘80s?",
            "Edmonton Oilers",
        ],
        ["Where did backgammon originate?", "In Persia"],
        ["How many cards are there in a deck of Uno?", "108"],
        ["In which board game do you try to solve a murder?", "Clue"],
        [
            "In chess, the queen has the combined movement of which two pieces?",
            "bishop and rook",
        ],
        [
            "Which of these games includes the phrase “Do not pass go, do not collect $200”?",
            "Monopoly",
        ],
        ["The video game “Happy Feet” features what animals?", "Penguins"],
        [
            "What classic video game requires you to eat all the dots throughout a maze?",
            "Pac-Man",
        ],
        [
            "Which Street Fighter character wears a white outfit and a red headband?",
            "Ryu",
        ],
        ["“Astro Boy” is what genre of a video game?", "Action"],
        ["What sport is featured in the video game “FIFA”?", "Soccer"],
        ["What is the common name for dried plums?", "Prunes"],
        ["What name does deer meat go by?", "Venison"],
        ["What other name does “corn” go by?", "Maize"],
        ["What’s the primary ingredient in hummus?", "Chickpeas"],
        ["Which country produces the most coffee in the world?", "Brazil"],
        ["Which country invented tea?", "China"],
        ["Which kind of alcohol is Russia notoriously known for?", "Vodka"],
        ["What is the national dish of Spain?", "Paella"],
        ["Which European nation was said to invent hot dogs?", "Germany"],
        ["Which country is responsible for giving us pizza and pasta?", "Italy"],
        ["Which organ has four chambers?", "The heart"],
        ["In which body part can you find the femur?", "Leg"],
        ["What is your body’s largest organ?", "The skin"],
        ["What kind of cells are found in the brain?", "Neurons"],
        ["Which bone are babies born without?", "Knee cap"],
        ["About how many taste buds does the average human tongue have?", "10,000"],
        ["What percentage of our bodies is made up of water?", "60-65%"],
        ["Which element is said to keep bones strong?", "Calcium"],
        [
            "What does the acronym AIDS stand for?",
            "Acquired Immune Deficiency Syndrome",
        ],
        ["How many times does the heartbeat per day?", "About 100,000"],
    ],
    "Category 4": [
        ["Who is the richest person in the world as of 2021?", "Elon Musk"],
        ["Bill Gates is the founder of which company?", "Microsoft"],
        ["In what year did Steve Jobs die?", "2011"],
        ["Larry Page is the CEO of which company?", "Google"],
        ["Richard Branson is the owner of which airline?", "Virgin Atlantic"],
        ["What vehicle is Volkswagen best known for in the world?", "The Beetle"],
        ["Which watch company has a pointed crown as its logo?", "Rolex"],
        ["What is the slogan of Apple Inc.?", "Think different"],
        ["What is Hewlett Packard (HP) originally known for?", "Printers"],
        ["How many stripes does Adidas have?", "1949"],
        [
            "Which actor appeared in films “Face Off” and “Ghost Rider”?",
            "Nicholas Cage",
        ],
        ["Who played Wolverine?", "Hugh Jackman"],
        ["Which actress won the Oscar for Best Actress in 2003?", "Nicole Kidman"],
        ["The Young Victoria was played by which British actress?", "Emily Blunt"],
        ["How old was Coco Gauff when she first beat Venus Williams?", "15"],
        [
            "In which year did Usain Bolt set his 100m in 9.58 seconds world record?",
            "2009",
        ],
        ["How many times had Rafael Nadal won the French Open by March 2020?", "12"],
        [
            "When Michael Jordan played for the Chicago Bulls, how many NBA Championships did he win?",
            "Six",
        ],
        [
            "Who did Forbes name the youngest self-made billionaire in 2019?",
            "Kylie Jenner",
        ],
        [
            "Which Dutch makeup artist came out as being transgender in 2020?",
            "De Jager",
        ],
        [
            "Who played Anita in the first Broadway production of West Side Story?",
            "Chita Rivera",
        ],
        ["In which US city is Broadway located?", "New York City"],
        ["What is the longest-running Broadway show?", "The Phantom of the Opera"],
        [
            "Which show is the highest-grossing production on Broadway ever?",
            "The Lion King",
        ],
        ["In what year was Broadway established?", "1750"],
        ["In which period did ballet originate?", "Italian Renaissance"],
        [
            "During which time of the year is the Nutchracker primarily performed?",
            "During Christmas season",
        ],
        ["What French ballet term means ‘in front’?", "Devant"],
        [
            "Who was the greatest male ballet dancer of the early 20th century?",
            "Vaslav Nijinsky",
        ],
        ["What is a plié in ballet?", "Bending at the knees"],
        ["Which American president was involved in the Watergate scandal?", "Nixon"],
        [
            "What are the surnames of the father-son duos who both served as US presidents?",
            "Adams and Bush",
        ],
        ["How many presidents have been impeached?", "Three"],
        [
            "Before the laws were changed in 2000, how long was a French president’s term?",
            "Seven years",
        ],
        [
            "Who has been the longest-serving monarch of the United Kingdom?",
            "Queen Elizabeth II",
        ],
        [
            "World War I began with the death of Archduke Franz Ferdinand, of which country?",
            "Austria",
        ],
        [
            "Donald Trump and which North Korean leader are known to trade threats over the internet?",
            "Kim Jong Un",
        ],
        [
            "What was Mao Zedong famous for?",
            "Leading the Communist Party of China to victory during a Civil War",
        ],
        [
            "Leader and political icon Nelson Mandela was from which African country?",
            "South Africa",
        ],
        [
            "The largest political party in South Africa, the ANC, stands for what?",
            "African National Congress",
        ],
        [
            "What is the legal term for a voluntary written statement made under oath?",
            "Affidavit",
        ],
        [
            "What is the name of the classification of crime which is less serious than a felony?",
            "Misdemeanor",
        ],
        ["A verdict is a…?", "Decision or judgment"],
        [
            "What is evidence in court, where a person tells everything they saw or know?",
            "Testimony",
        ],
        [
            "Who is the group of people sworn to make a decision/deliver a verdict in court?",
            "Jury",
        ],
        ["What was the verdict in the O.J. Simpson murder trial?", "Not guilty"],
        ["How many homicides did Ted Bundy admit to?", "30"],
        ["Ted Kaczynski was a former graduate of which university?", "Harvard"],
        [
            "Gregory Lee Johnson was convicted in Texas for what in 1989?",
            "Burning the flag",
        ],
        ["Butch Cassidy was famous for doing what?", "Stealing"],
    ],
    "Category 5": [
        ["In “The Farmer in the Dell,” what did the cat take?", "The rat"],
        ["What did the “Itsy Bitsy Spider” climb up?", "The waterspout"],
        ["What did the “Three Little Kittens” lose?", "Their mittens"],
        ["How many bags of wool did “Baa Baa Black Sheep” have?", "Three"],
        ["Why did Jack and Jill go up the hill?", "To fetch a pail of water"],
        ["How can a man go eight days without sleep?", "By sleeping during the night"],
        [
            "How can you drop a raw egg on the concrete floor without cracking it?",
            "The egg won’t crack the concrete floor",
        ],
        [
            "If there are six apples and you take away four, how many do you have?",
            "Four",
        ],
        ["What goes up and down, but still remains in the same place?", "Stairs"],
        ["What gets wetter and wetter the more it dries?", "A towel"],
        ["What holiday is called “turkey day”?", "Thanksgiving Day"],
        ["In the US, what month is Labor Day in?", "September"],
        ["When is Canada Day?", "July 1st"],
        ["Mexico’s Dia de los Muertos, means what in English?", "Day of the Dead"],
        ["Oktoberfest in Germany is celebrated with what drink?", "Beer"],
        [
            "What is celebrated on the 2nd Saturday in June in the United Kingdom?",
            "The Queen’s Official Birthday",
        ],
        ["Which country celebrates the Storming of the Bastille?", "France"],
        ["Mahatma Gandi’s birthday is a national holiday in which country?", "India"],
        ["The Chinese New Year is celebrated on what day and month?", "25th January"],
        ["Independence Day in Cambodia is when?", "9th November"],
        ["How many books are in the Catholic Bible?", "Seventy-three"],
        ["How many fish were used to feed the 5,000 along with the loaves?", "Two"],
        [
            "Which god is considered the “destroyer” and is part of the Hindu Trinity?",
            "Shiva",
        ],
        ["The mother of the youngest Pandavas is?", "Madri"],
        ["The Islamic calendar is based on which cycle?", "Lunar"],
        ["Who was the last prophet in Islam?", "Muhammad"],
        ["“Cohen” is Hebrew for what?", "Priest"],
        [
            "What is the Hebrew term for a good deed done out of a sense of religious duty?",
            "Mitzvah",
        ],
        ["In which country was Buddha born?", "Nepal"],
        [
            "Where does Buddhism fall in a ranking of the world’s largest religion?",
            "Fifth",
        ],
        ["What is the name of the home of the Greek Gods?", "Olympus"],
        ["Which warrior’s weakness was their heel?", "Achilles"],
        ["Who was the messenger of the gods?", "Hermes"],
        ["What’s the name of the paradise warriors go to after death?", "Valhalla"],
        ["Thor was the son of which God?", "Odin"],
        ["Romulus and Remus were raised by what animal?", "A she-wolf"],
        ["The Roman God of War inspired the name of which planet?", "Mars"],
        ["What was the name of the Egyptian God of the Sun?", "Ra"],
        ["Anubis, the God of Death, had the head of a...?", "Jackal"],
        [
            "Set throws Osiris into which river, after tricking him into a coffin?",
            "The Nile",
        ],
        ["How long is the gestation period of an African elephant?", "22 months"],
        ["What’s the scientific name of a wolf?", "Canis lupus"],
        ["What is a female donkey called?", "A Jenny"],
        ["Which mammal has no vocal cords?", "Giraffe"],
        ["What’s the fastest land animal in the world?", "The cheetah"],
        ["How many eyes does a bee have?", "Five"],
        ["Which animal symbolizes good luck in Europe?", "Ladybug"],
        ["What name is used to refer to a group of frogs?", "An army"],
        ["How many hearts does an octopus have?", "Three"],
        ["Do sponges have hearts?", "No"],
    ],
}
